# Generated by Django 5.2.1 on 2025-07-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('num_copies', models.IntegerField()),
                ('pages_num', models.CharField(max_length=255)),
                ('orientation', models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], max_length=50)),
                ('color_mode', models.CharField(choices=[('Black and White', 'Black and White'), ('Color', 'Color')], max_length=50)),
                ('paper_size', models.CharField(choices=[('Long', 'Long'), ('Letter', 'Letter'), ('A4', 'A4'), ('Unsupported', 'Unsupported')], max_length=50)),
                ('paper_quality', models.CharField(choices=[('70', '70 GSM'), ('80', '80 GSM')], max_length=50)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('doc_status', models.CharField(choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Printing', 'Printing'), ('Finished', 'Finished')], default='Pending', max_length=50)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('time_submitted', models.DateTimeField()),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Comment', 'Comment'), ('Report a Problem', 'Report a Problem')], max_length=20)),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('printer_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_status', models.CharField(max_length=50)),
                ('paper_assigned', models.CharField(choices=[('Long', 'Long'), ('Letter', 'Letter'), ('A4', 'A4'), ('Unsupported', 'Unsupported')], max_length=50)),
                ('paper_quality', models.CharField(choices=[('70', '70 GSM'), ('80', '80 GSM')], max_length=50)),
                ('last_checked', models.DateTimeField()),
                ('printer_serialNumber', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'printers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.document')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='printed_at',
            field=models.ForeignKey(blank=True, db_column='printed_at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_documents', to='portal.printer'),
        ),
        migrations.AddField(
            model_name='document',
            name='printer_assigned',
            field=models.ForeignKey(blank=True, db_column='printer_assigned_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to='portal.printer'),
        ),
        migrations.CreateModel(
            name='RerouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reroute_history', to='portal.document')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.printer')),
            ],
            options={
                'verbose_name': 'Reroute history',
                'verbose_name_plural': 'Reroute history',
                'db_table': 'reroute_history',
                'ordering': ['timestamp'],
            },
        ),
    ]
