# Generated by Django 5.2.1 on 2025-06-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('num_copies', models.IntegerField()),
                ('pages_num', models.IntegerField()),
                ('orientation', models.CharField(max_length=50)),
                ('color_mode', models.CharField(max_length=50)),
                ('paper_size', models.CharField(max_length=50)),
                ('paper_quality', models.CharField(max_length=50)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('doc_status', models.CharField(max_length=50)),
                ('time_submitted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=255)),
                ('printer_status', models.CharField(max_length=50)),
                ('paper_assigned', models.CharField(max_length=50)),
                ('paper_quality', models.CharField(max_length=50)),
                ('last_checked', models.DateTimeField()),
                ('printer_serialNumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='printed_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_documents', to='portal.printer'),
        ),
        migrations.AddField(
            model_name='document',
            name='printer_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to='portal.printer'),
        ),
    ]
