# Generated by Django 5.2.1 on 2025-06-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='printer',
            name='paper_assigned',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short'), ('A4', 'A4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='paper_quality',
            field=models.CharField(choices=[('70', '70 GSM'), ('80', '80 GSM')], max_length=50),
        ),
        migrations.CreateModel(
            name='RerouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reroute_history', to='portal.document')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.printer')),
            ],
            options={
                'db_table': 'document_printer_history',
                'ordering': ['timestamp'],
            },
        ),
    ]
