# Generated by Django 5.2.1 on 2025-06-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_users',
        ),
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='printer',
            table='printers',
        ),
    ]
