# Generated by Django 5.2.1 on 2025-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='printer_serialNumber',
            new_name='ip_address',
        ),
        migrations.AddField(
            model_name='printer',
            name='node_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
