# Generated by Django 5.2.1 on 2025-06-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_printer_model_name_alter_printer_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reroutehistory',
            options={'ordering': ['timestamp'], 'verbose_name': 'Reroute history', 'verbose_name_plural': 'Reroute history'},
        ),
        migrations.AlterModelTable(
            name='reroutehistory',
            table='reroute_history',
        ),
    ]
