# Generated by Django 5.2.1 on 2025-06-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
