# Generated by Django 5.2.1 on 2025-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_printer_serialnumber_printer_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='ink_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
