# Generated by Django 5.2.1 on 2025-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_reroutehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Printing', 'Printing'), ('Finished', 'Finished')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages_num',
            field=models.CharField(max_length=255),
        ),
    ]
