# Generated by Django 5.2.1 on 2025-07-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_printer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='ink_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
