# Generated by Django 5.2.1 on 2025-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_printer_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='paper_assigned',
            field=models.CharField(choices=[('Long', '8.5in x 13in (Long)'), ('Short', '8.5in x 11in (Short)'), ('A4', '8.3in x 11.7in (A4)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='paper_quality',
            field=models.CharField(choices=[('70', '70 GSM'), ('80', '80 GSM')], max_length=50),
        ),
    ]
