# Generated by Django 5.2.1 on 2025-07-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_printer_ink_status_alter_printer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages_printed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
