# Generated by Django 5.2.1 on 2025-06-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_document_doc_status_alter_document_pages_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='color_mode',
            field=models.CharField(choices=[('Black and White', 'Black and White'), ('Color', 'Color')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='orientation',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='paper_quality',
            field=models.CharField(choices=[('70', '70 GSM'), ('80', '80 GSM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='paper_size',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short'), ('A4', 'A4')], max_length=50),
        ),
    ]
