# Generated by Django 5.2.1 on 2025-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_document_color_mode_alter_document_orientation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='paper_size',
            field=models.CharField(choices=[('Long', 'Long'), ('Letter', 'Letter'), ('A4', 'A4'), ('Unsupported', 'Unsupported')], max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='paper_assigned',
            field=models.CharField(choices=[('Long', 'Long'), ('Letter', 'Letter'), ('A4', 'A4'), ('Unsupported', 'Unsupported')], max_length=50),
        ),
    ]
