# Generated by Django 5.2.1 on 2025-09-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_set_default_chime_for_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsound',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
