# Generated by Django 5.2.1 on 2025-09-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_volume_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='machine_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
