# Generated by Django 5.2.1 on 2025-09-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_printer_machine_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='machine_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
