# Generated by Django 5.2.1 on 2025-09-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_printer_machine_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='machine_info',
        ),
    ]
