# Generated by Django 5.2.1 on 2026-02-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_printer_machine_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReprintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('page_range', models.CharField(blank=True, default='all', max_length=20)),
                ('specific_pages', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('reprinted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_logs', to='portal.document')),
                ('printer_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.printer')),
            ],
            options={
                'db_table': 'document_reprint_logs',
                'ordering': ['-reprinted_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_id', models.CharField(max_length=255)),
                ('document_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('problem_type', models.CharField(choices=[('quality', 'Low Quality / Damage'), ('missing-pages', 'Some Pages Missing / Blank'), ('no-print', 'Whole Document Did Not Print'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('page_range', models.CharField(blank=True, default='all', max_length=20)),
                ('specific_pages', models.CharField(blank=True, default='', max_length=100)),
                ('was_reprinted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='portal.document')),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
