# Generated by Django 5.2.1 on 2026-02-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_documentreprintlog_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Printing', 'Printing'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled'), ('Picked Up', 'Picked Up')], default='Pending', max_length=50),
        ),
    ]
