# Generated by Django 5.2.1 on 2026-02-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_document_doc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
