# Generated by Django 5.2.1 on 2026-02-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_add_voucher_code_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
