# Generated by Django 5.2.1 on 2026-02-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_add_phone_number_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='klcis_transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
