# Generated by Django 5.2.1 on 2026-02-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_add_klcis_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='receipt_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='receipt_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_screenshots/'),
        ),
    ]
