# Generated by Django 5.2.1 on 2026-02-13 09:15

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_add_receipt_fields_to_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='receipt_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.receipt_upload_path),
        ),
    ]
