# Generated by Django 5.2.1 on 2026-02-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_used_klcis_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Initial credit when created', max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text='Current available balance', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='False when fully used or expired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='120 days from creation')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Voucher Credit',
                'verbose_name_plural': 'Voucher Credits',
                'db_table': 'voucher_credits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='usedklcistransaction',
            options={'verbose_name': 'Used KLCiS Transaction', 'verbose_name_plural': 'Used KLCiS Transactions'},
        ),
    ]
