# Generated by Django 5.2.1 on 2026-02-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_voucher_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercredit',
            name='last_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='CID of the last transaction that created/updated this credit', max_length=255, null=True),
        ),
    ]
