# Generated by Django 5.2.1 on 2026-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_add_last_customer_id_to_vouchercredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='last_refill_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='tray_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='tray_level',
            field=models.CharField(default='Needs Refill', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='paper_quality',
            field=models.CharField(choices=[('', 'None'), ('70', '70 GSM'), ('80', '80 GSM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='paper_size',
            field=models.CharField(choices=[('', 'None'), ('Long', 'Long'), ('Letter', 'Letter'), ('A4', 'A4'), ('Unsupported', 'Unsupported')], max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='paper_assigned',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Long', 'Long'), ('Letter', 'Letter'), ('A4', 'A4'), ('Unsupported', 'Unsupported')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='paper_quality',
            field=models.CharField(blank=True, choices=[('', 'None'), ('70', '70 GSM'), ('80', '80 GSM')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_status',
            field=models.CharField(default='Offline', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('voided', 'Voided'), ('refunded', 'Refunded')], default='open', max_length=50),
        ),
    ]
