# Generated by Django 5.2.1 on 2026-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_printer_last_refill_time_printer_tray_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
