# Generated by Django 5.2.1 on 2026-03-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='gcash_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='refund_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='refund_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Ticket Created'), ('status_changed', 'Status Changed'), ('refund_approved', 'Refund Approved'), ('refund_completed', 'Refund Completed'), ('refund_rejected', 'Refund Rejected'), ('voided', 'Ticket Voided'), ('note_added', 'Note Added'), ('verified', 'Ticket Verified')], max_length=30)),
                ('old_status', models.CharField(blank=True, default='', max_length=50)),
                ('new_status', models.CharField(blank=True, default='', max_length=50)),
                ('performed_by', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='portal.supportticket')),
            ],
            options={
                'db_table': 'ticket_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
