# Generated by Django 5.2.1 on 2026-03-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_supportticket_gcash_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='tray_current_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
