# Generated by Django 5.2.1 on 2026-03-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_add_tray_current_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='data_purged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='data_retention_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
