# Generated by Django 5.2.1 on 2026-03-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_add_data_retention_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Ticket Created'), ('status_changed', 'Status Changed'), ('refund_approved', 'Refund Approved'), ('refund_completed', 'Refund Completed'), ('refund_rejected', 'Refund Rejected'), ('voided', 'Ticket Voided'), ('note_added', 'Note Added'), ('verified', 'Ticket Verified'), ('data_purged', 'Data Purged')], max_length=30),
        ),
        migrations.CreateModel(
            name='PrinterStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('ink_status', models.CharField(blank=True, default='', max_length=50)),
                ('paper_level', models.CharField(blank=True, default='', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='portal.printer')),
            ],
            options={
                'db_table': 'printer_status_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='printer_sta_timesta_5e4ea9_idx'), models.Index(fields=['printer', '-timestamp'], name='printer_sta_printer_d6bc13_idx')],
            },
        ),
    ]
