# Generated by Django 5.2.1 on 2026-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_create_printer_status_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLifecycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=255)),
                ('customer_id', models.CharField(db_index=True, max_length=255)),
                ('doc_name', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.CharField(choices=[('uploaded', 'Uploaded'), ('pending', 'Pending'), ('queued', 'Queued'), ('printing', 'Printing'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('picked_up', 'Picked Up'), ('deleted', 'Deleted'), ('denied', 'Denied'), ('reprinted', 'Reprinted')], max_length=20)),
                ('printer_name', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_lifecycle_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['doc_id', '-timestamp'], name='document_li_doc_id_91a6dc_idx'), models.Index(fields=['customer_id', '-timestamp'], name='document_li_custome_d2df1a_idx')],
            },
        ),
    ]
