# Generated by Django 5.2.1 on 2026-03-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_create_document_lifecycle_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='verification_time_window',
            field=models.IntegerField(default=10, help_text='Time window (minutes) around ticket creation for printer status verification'),
        ),
    ]
