# Generated by Django 5.2.1 on 2026-03-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_add_verification_time_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='auto_ticket_timeout_minutes',
            field=models.IntegerField(default=5, help_text='Minutes a document stays Queued with empty queue before auto-triggering ticket popup'),
        ),
    ]
