# Generated by Django 5.2.1 on 2026-03-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_add_auto_ticket_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='related_doc_ids',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TicketProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipt_screenshots/proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_images', to='portal.supportticket')),
            ],
            options={
                'db_table': 'ticket_proof_images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
