# Generated by Django 5.2.1 on 2026-05-02 14:23

import django.db.models.deletion
from django.db import migrations, models


def _count_pages(pages_num):
    if not pages_num:
        return 0

    total_pages = 0
    for part in str(pages_num).split(','):
        part = part.strip()
        if not part:
            continue
        if '-' in part:
            try:
                start, end = map(int, part.split('-', 1))
            except (TypeError, ValueError):
                total_pages += 1
                continue
            total_pages += max((end - start) + 1, 0)
            continue
        total_pages += 1
    return total_pages


def backfill_audit_snapshots(apps, schema_editor):
    Payment = apps.get_model('portal', 'Payment')
    SupportTicket = apps.get_model('portal', 'SupportTicket')
    RerouteHistory = apps.get_model('portal', 'RerouteHistory')
    DocumentReprintLog = apps.get_model('portal', 'DocumentReprintLog')

    for payment in Payment.objects.select_related('doc').all().iterator():
        document = getattr(payment, 'doc', None)
        if not document:
            continue

        payment.customer_id_snapshot = payment.customer_id_snapshot or document.customer_id
        payment.doc_id_snapshot = payment.doc_id_snapshot or document.doc_id
        payment.document_name_snapshot = payment.document_name_snapshot or document.original_name or document.filename or ''
        if payment.num_copies_snapshot is None:
            payment.num_copies_snapshot = document.num_copies
        payment.pages_num_snapshot = payment.pages_num_snapshot or document.pages_num or ''
        if payment.total_pages_snapshot is None:
            payment.total_pages_snapshot = _count_pages(document.pages_num)
        payment.orientation_snapshot = payment.orientation_snapshot or document.orientation or ''
        payment.color_mode_snapshot = payment.color_mode_snapshot or document.color_mode or ''
        payment.paper_size_snapshot = payment.paper_size_snapshot or document.paper_size or ''
        payment.paper_quality_snapshot = payment.paper_quality_snapshot or document.paper_quality or ''
        payment.save()

    for ticket in SupportTicket.objects.select_related('document').all().iterator():
        document = getattr(ticket, 'document', None)
        if document:
            ticket.document_id_snapshot = ticket.document_id_snapshot or document.doc_id
            ticket.document_name = ticket.document_name or document.original_name or document.filename or ''
        elif not ticket.document_id_snapshot and getattr(ticket, 'document_id', ''):
            ticket.document_id_snapshot = ticket.document_id

        if ticket.payment_amount_snapshot is None or not ticket.payment_method_snapshot or not ticket.payment_verified_by_snapshot or ticket.payment_approved_at_snapshot is None:
            payment = None
            if ticket.document_id_snapshot:
                payment = Payment.objects.filter(
                    models.Q(doc_id_snapshot=ticket.document_id_snapshot) |
                    models.Q(doc_id=ticket.document_id_snapshot)
                ).order_by('-approved_at', '-id').first()
            if payment:
                if ticket.payment_amount_snapshot is None:
                    ticket.payment_amount_snapshot = payment.price
                if not ticket.payment_method_snapshot:
                    ticket.payment_method_snapshot = payment.payment_method or ''
                if not ticket.payment_verified_by_snapshot:
                    ticket.payment_verified_by_snapshot = payment.approved_by or ''
                if ticket.payment_approved_at_snapshot is None:
                    ticket.payment_approved_at_snapshot = payment.approved_at
        ticket.save()

    for history in RerouteHistory.objects.select_related('document', 'printer').all().iterator():
        document = getattr(history, 'document', None)
        printer = getattr(history, 'printer', None)
        if document:
            history.doc_id_snapshot = history.doc_id_snapshot or document.doc_id
            history.customer_id_snapshot = history.customer_id_snapshot or document.customer_id
            history.doc_name_snapshot = history.doc_name_snapshot or document.original_name or document.filename or ''
        if printer:
            history.printer_name_snapshot = history.printer_name_snapshot or printer.name
        history.save()

    for reprint in DocumentReprintLog.objects.select_related('document').all().iterator():
        document = getattr(reprint, 'document', None)
        if not document:
            continue
        reprint.doc_id_snapshot = reprint.doc_id_snapshot or document.doc_id
        reprint.customer_id_snapshot = reprint.customer_id_snapshot or document.customer_id
        reprint.doc_name_snapshot = reprint.doc_name_snapshot or document.original_name or document.filename or ''
        reprint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_sitesetting_block_payment_when_printers_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreprintlog',
            name='customer_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentreprintlog',
            name='doc_id_snapshot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentreprintlog',
            name='doc_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='color_mode_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_id_snapshot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='doc_id_snapshot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='document_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='num_copies_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='orientation_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='pages_num_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='paper_quality_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='paper_size_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_pages_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='evidence_redacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reroutehistory',
            name='customer_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reroutehistory',
            name='doc_id_snapshot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reroutehistory',
            name='doc_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reroutehistory',
            name='printer_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='document_id_snapshot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='payment_amount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='payment_approved_at_snapshot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='payment_method_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='payment_verified_by_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentreprintlog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprint_logs', to='portal.document'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.document'),
        ),
        migrations.AlterField(
            model_name='reroutehistory',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reroute_history', to='portal.document'),
        ),
        migrations.CreateModel(
            name='VoucherCreditAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code_snapshot', models.CharField(db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('created', 'Created'), ('reserved', 'Reserved'), ('redeemed', 'Redeemed'), ('restored', 'Restored'), ('reactivated', 'Reactivated'), ('deactivated', 'Deactivated'), ('expired', 'Expired'), ('deleted', 'Deleted')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('performed_by', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='portal.vouchercredit')),
            ],
            options={
                'db_table': 'voucher_credit_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_audit_snapshots, migrations.RunPython.noop),
    ]
