# Generated by Django 5.2.1 on 2026-05-02 15:20

from django.db import migrations, models


def backfill_pricing_threshold_snapshot(apps, schema_editor):
    Payment = apps.get_model('portal', 'Payment')
    SiteSetting = apps.get_model('portal', 'SiteSetting')

    site = SiteSetting.objects.filter(pk=1).first()
    default_threshold = site.color_full_threshold_percent if site else 10

    Payment.objects.filter(pricing_threshold_snapshot__isnull=True).update(
        pricing_threshold_snapshot=default_threshold,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_documentreprintlog_customer_id_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pricing_threshold_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='color_full_threshold_percent',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Percent of colored pixels at or above which a page is treated as full color', max_digits=5),
        ),
        migrations.RunPython(backfill_pricing_threshold_snapshot, migrations.RunPython.noop),
    ]
