# Generated by Django 5.2.1 on 2026-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_payment_pricing_threshold_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bw_price_70',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price for a black-and-white page on 70 GSM paper', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bw_price_80',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Price for a black-and-white page on 80 GSM paper', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='full_color_price',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Price for a full-color page', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='partial_color_price',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Price for a partially colored page', max_digits=10),
        ),
    ]
