from django.urls import path
from . import views

urlpatterns = [
    # Add your admin-specific URL patterns here
    path('portal/dashboard/', views.dashboard, name='dashboard'),
    path('portal/queue/', views.printing_queue, name='printing_queue'),
    path('portal/completed/', views.print_completed, name='print_completed'),
    path('portal/status/', views.printer_status, name='printer_status'),
    path('portal/settings/', views.account_settings, name='account_settings'),
    path('portal/vouchers/', views.voucher_management, name='voucher_management'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('thankyou/', views.thankyou_view, name='thankyou'),
    path('api/change-image-ajax/', views.change_image_ajax, name='change_image_ajax'),
    path('api/update-name/', views.update_name, name='update_name'),
    path('api/update-username/', views.update_username, name='update_username'),
    path('api/update-password/', views.update_password, name='update_password'),
    path('api/update-email/', views.update_email, name='update_email'),
    path('api/update-user-password/', views.update_user_password, name='update_user_password'),
    path('api/delete_user_ajax/', views.delete_user_ajax, name='delete_user_ajax'),
    path('api/add_user_ajax/', views.add_user_ajax, name='add_user_ajax'),
    path('api/feedback-comments/', views.feedback_comments_api, name='feedback_comments_api'),
    path('api/feedback-submit/', views.feedback_submit_api, name='feedback_submit_api'),
    path('api/problem-reports/', views.problem_reports_api, name='problem_reports_api'),
    path('api/update_printer_field/', views.update_printer_field, name='update_printer_field'),
    path('api/mark_printer_refilled/', views.mark_printer_refilled, name='mark_printer_refilled'),
    path('api/add_printer/', views.add_printer, name='add_printer'),
    path('api/edit_printer/', views.edit_printer, name='edit_printer'),
    path('api/delete_printer/', views.delete_printer, name='delete_printer'),
    path('api/search_customer/', views.search_customer, name='search_customer'),
    path('api/get-active-tickets/', views.get_active_tickets_api, name='get_active_tickets_api'),
    path('payment/', views.payment, name='payment'),
    path('api/check-voucher/', views.check_voucher_api, name='check_voucher_api'),
    path('portal/api/vouchers/', views.voucher_list_api, name='voucher_list_api'),
    path('portal/api/generate-voucher/', views.generate_voucher_api, name='generate_voucher_api'),
    path('portal/api/toggle-voucher/', views.toggle_voucher_api, name='toggle_voucher_api'),
    path('portal/api/delete-voucher/', views.delete_voucher_api, name='delete_voucher_api'),
    path('api/deny-all-documents/', views.deny_all_documents, name='deny_all_documents'),
    path('api/approve-all-documents/', views.approve_all_documents, name='approve_all_documents'),
    path('api/deny-document/', views.deny_document, name='deny_document'),
    path('api/approve-document/', views.approve_document, name='approve_document'),
    path('api/update-notification-prefs/', views.update_notification_prefs, name='update_notification_prefs'),
    path('api/get-notification-prefs/', views.get_notification_prefs, name='get_notification_prefs'),
    path('api/get-customer-sound-prefs/', views.get_customer_sound_prefs, name='get_customer_sound_prefs'),
    path('api/update-customer-sound-prefs/', views.update_customer_sound_prefs, name='update_customer_sound_prefs'),
    path('sse/printer-status/', views.printer_status_stream, name='printer_status_stream'),
    path('sse/dashboard-status/', views.dashboard_status_stream, name='dashboard_status_stream'),
    path('sse/customer-documents/<str:customer_id>/', views.customer_documents_stream, name='customer_documents_stream'),
    path('api/picked-up-document/', views.picked_up_document, name='picked_up_document'),
    path('api/finish-transaction/', views.finish_transaction, name='finish_transaction'),
    path('api/void-ticket/', views.void_ticket, name='void_ticket'),
    path('api/refund-ticket/', views.refund_ticket, name='refund_ticket'),
    path('api/complete-refund/', views.complete_refund, name='complete_refund'),
    path('api/purge-ticket-data/', views.purge_ticket_data, name='purge_ticket_data'),
    path('api/ticket-audit-log/', views.get_ticket_audit_log, name='get_ticket_audit_log'),
]